name: Publish --canary

on:
  push:
    branches:
      - main
  
  # Allow manual trigger for testing
  workflow_dispatch:

jobs:
  publish:
    name: Main
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      id-token: write # for npm provenance
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies
        with:
          registry-url: 'https://registry.npmjs.org'
        
      - name: Run tests
        run: pnpm test
        
      - name: Build project
        run: pnpm build
        
      # - name: Configure npm authentication
      #   run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
        
      # - name: Publish canary to npm
      #   run: pnpm tsx versace.ts --canary --provenance
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
