name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  test:
    name: Test with Node ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Run tests
        run: pnpm test
      
      - name: Build
        run: pnpm build
